services:
    mongodb:
        image: mongo:4.4
        container_name: postmon_mongodb
        restart: unless-stopped
        volumes:
            - mongodb_data:/data/db
        environment:
            MONGO_INITDB_DATABASE: postmon
        healthcheck:
            test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 5

    postmon:
        build: .
        container_name: postmon_app
        restart: unless-stopped
        ports:
            - "9876:9876"
        depends_on:
            mongodb:
                condition: service_healthy
        environment:
            - POSTMON_DB_HOST=mongodb
            - POSTMON_DB_PORT=27017
            - POSTMON_DB_NAME=postmon
        volumes:
            - ./data:/srv/postmon/data

volumes:
    mongodb_data:
